# EComData.py
from datetime import datetime
from typing import Dict
from database import save_conversation  # local DB save function

ecommerce_training_data = [
    {
        "topic": "Market Overview",
        "questions": [
            "What is the size of Pakistan's eCommerce market in 2024?",
            "How much is Pakistan's eCommerce market projected to grow by 2027?",
            "What is the current CAGR for Pakistan's eCommerce industry?",
            "How much retail eCommerce contributes to the overall digital economy?"
        ],
        "follow_ups": [
            "Has the eCommerce growth rate been steady over the years?",
            "How did COVID-19 affect Pakistan's eCommerce growth?",
            "Which factors are driving this market growth?",
            "Can you provide a comparison between 2020 and 2024 growth?"
        ],
        "cross_questions": [
            "Is Pakistan's eCommerce growth faster than India's?",
            "How does Pakistan compare to Southeast Asian countries in eCommerce?",
            "Does this growth translate to increased employment opportunities?",
            "What are the biggest companies contributing to this market share?"
        ],
        "answers": {
            "size_2024": "Pakistan's eCommerce market reached approximately USD 7.7 billion in 2024.",
            "growth_projection": "It is expected to grow by around 17% CAGR between 2024 and 2027.",
            "covid_impact": "The pandemic accelerated online shopping, especially in urban areas.",
            "comparison": "In 2020, total online sales were around USD 3.2 billion, increasing to USD 7.7 billion by 2024."
        }
    },
    {
        "topic": "Payment Methods",
        "questions": [
            "What are the most common payment methods used in Pakistan's eCommerce?",
            "What percentage of payments are made through cash on delivery?",
            "How popular are digital wallets and card payments?",
            "What is being done to improve digital payment adoption?"
        ],
        "follow_ups": [
            "Why is cash on delivery still so dominant?",
            "Are Pakistani consumers hesitant to use online banking?",
            "What is the government's role in improving digital payments?",
            "Are fintech companies contributing to better payment experiences?"
        ],
        "cross_questions": [
            "Does the preference for cash affect eCommerce profitability?",
            "How do international platforms like Amazon deal with COD in Pakistan?",
            "Are rural customers more likely to use COD than urban ones?",
            "What challenges exist in integrating mobile wallets with online stores?"
        ],
        "answers": {
            "cod_share": "Around 75% of eCommerce transactions in Pakistan are done via Cash on Delivery.",
            "card_usage": "Debit cards account for 9%, credit cards 8%, and digital wallets 4% of transactions.",
            "government_initiative": "The State Bank of Pakistan and NADRA are promoting digital payments through Raast and mobile wallet incentives.",
            "consumer_behavior": "Trust and logistics issues make COD the preferred payment choice."
        }
    },
    {
        "topic": "Devices and Platforms",
        "questions": [
            "Which devices do most people in Pakistan use for online shopping?",
            "Is mobile eCommerce more common than desktop shopping?",
            "What is the share of mobile transactions in total sales?",
            "Are there any notable platforms leading mobile eCommerce?"
        ],
        "follow_ups": [
            "Which mobile apps are most popular for shopping in Pakistan?",
            "Do most eCommerce sites have mobile-friendly versions?",
            "Are 4G and 5G rollouts affecting mobile shopping habits?",
            "How does mobile eCommerce compare with desktop in user engagement?"
        ],
        "cross_questions": [
            "Are mobile shoppers younger on average?",
            "How do Pakistani mobile eCommerce trends compare to global averages?",
            "Are mobile payments more secure in Pakistan now?",
            "Do logistics apps integrate directly with eCommerce platforms?"
        ],
        "answers": {
            "mobile_share": "Around 80% of all eCommerce transactions in Pakistan happen via mobile devices.",
            "platforms": "Daraz, Yayvo, and HumMart are the top online shopping platforms in Pakistan.",
            "connectivity": "Improved 4G coverage and cheaper smartphones have boosted mobile eCommerce significantly."
        }
    },
    {
        "topic": "Regulation and Policy",
        "questions": [
            "What recent policies has Pakistan introduced to support eCommerce?",
            "What are the key points of Pakistan's eCommerce Policy 2.0 (2025-2030)?",
            "Has the government reduced taxes on online sellers?",
            "What regulatory changes have affected cross-border eCommerce?"
        ],
        "follow_ups": [
            "Why was the duty-free parcel threshold reduced?",
            "What impact did this change have on imported goods?",
            "How are digital taxes being handled for international platforms?",
            "What is the goal behind Policy 2.0?"
        ],
        "cross_questions": [
            "Is Policy 2.0 expected to attract foreign investment?",
            "Are there similar eCommerce policies in other South Asian countries?",
            "What are the main challenges in policy implementation?",
            "Does the new policy include consumer protection measures?"
        ],
        "answers": {
            "policy_summary": "The Pakistan eCommerce Policy 2.0 (2025-2030) aims to expand digital trade, improve payments, logistics, and consumer protection.",
            "duty_threshold": "The duty-free import threshold was reduced from Rs. 5,000 to Rs. 500 to control informal imports.",
            "digital_tax": "A 5% fixed tax on digital platforms was introduced but later rolled back to support growth.",
            "policy_goal": "It focuses on building digital trust, promoting exports, and improving governance through data."
        }
    },
    {
        "topic": "Challenges",
        "questions": [
            "What are the main challenges facing Pakistan's eCommerce sector?",
            "How do logistics affect online shopping growth?",
            "Is consumer trust still a problem in Pakistan's eCommerce market?",
            "What are the barriers to cross-border online trade?"
        ],
        "follow_ups": [
            "How are logistics companies trying to overcome these challenges?",
            "Are there efforts to improve customer data security?",
            "What initiatives promote digital literacy among small sellers?",
            "Are government or private sectors working on consumer protection?"
        ],
        "cross_questions": [
            "Do other developing countries face similar challenges?",
            "Can Pakistan use blockchain for better supply chain transparency?",
            "How important is customer service quality for eCommerce growth?",
            "Are counterfeit goods still an issue online?"
        ],
        "answers": {
            "key_challenges": "Low digital payment adoption, weak logistics, consumer mistrust, and high return rates are major challenges.",
            "solutions": "Improving fintech access, enhancing courier infrastructure, and enforcing stronger regulations are being discussed.",
            "trust_issues": "Consumer trust is improving slowly as platforms focus on secure payments and authentic products."
        }
    },
    {
        "topic": "E-Commerce Insights",
        "questions": [
            "What is the most popular product category in Pakistan's ecommerce dataset?",
            "What is the average selling price across all products?",
            "Which payment methods are most frequently used by customers?",
            "What business insight can be drawn from high average order totals?",
            "How can ecommerce platforms increase sales in categories like Mobiles & Tablets?",
            "Which month shows the highest sales trend in the dataset?",
            "Why is COD (Cash on Delivery) still a dominant payment method in Pakistan?",
            "What factors influence the grand total of an order?",
            "How does discount amount impact customer buying behavior?",
            "Which product categories have the highest quantity ordered overall?",
            "What could cause an order to be canceled in the dataset?",
            "What does the 'status' column indicate in the ecommerce dataset?",
            "Why is Women's Fashion a top category in Pakistan's ecommerce market?",
            "What business strategy can boost sales in the Beauty & Grooming category?",
            "Which factor directly affects the quantity ordered by customers?",
            "Why is tracking the 'created_at' date important in ecommerce data?",
            "What insight can be drawn from 'Year' and 'Month' columns in the dataset?",
            "Why is repeat purchasing an important KPI for ecommerce?",
            "How do online promotions impact sales in Pakistan’s ecommerce sector?",
            "What role does logistics play in customer satisfaction?",
            "Why do some customers prefer prepayment methods over COD?",
            "What can the 'grand_total' column tell about business health?",
            "Which city likely generates the most ecommerce orders in Pakistan?",
            "What is the relationship between price and order quantity?",
            "How can data-driven marketing improve sales conversion?",
            "What advantage do sellers gain from analyzing sales_commission_code data?",
            "Why should ecommerce businesses monitor order status regularly?",
            "What impact do customer reviews have on online sales?",
            "Why do some months show low ecommerce activity?",
            "How can analyzing top categories help in business strategy?",
            "Why does product availability affect customer loyalty?",
            "How can ecommerce platforms manage return rates effectively?",
            "Why is product pricing important in Pakistan’s online market?",
            "What marketing approach works best for Men’s Fashion online?",
            "Why does Women's Fashion lead in product diversity?",
            "What is the advantage of analyzing ‘Customer Since’ data?",
            "How can ecommerce businesses identify their most valuable customers?",
            "Why is it useful to know the fiscal year (FY) in ecommerce data?",
            "What causes sudden spikes in ecommerce orders?",
            "How do payment methods influence customer retention?",
            "What are the most common reasons for refunds?",
            "How can customer segmentation improve marketing efficiency?",
            "Why is monitoring average order value (AOV) important?",
            "What does 'qty_ordered' reveal about demand trends?",
            "Why is data-driven decision-making critical for ecommerce?",
            "How can ecommerce companies boost performance in low-selling months?",
            "What business lesson can be drawn from frequently canceled orders?",
            "How do customer demographics impact product demand?",
            "Why are mobile-optimized sites essential for ecommerce?",
            "What are the benefits of tracking monthly sales trends?",
            "Why do ecommerce businesses analyze average selling price (ASP)?",
            "How can customer feedback improve operational efficiency?",
            "Why is digital marketing essential for ecommerce growth?",
            "What can be inferred from increasing online payment adoption?",
            "What are the challenges of handling COD payments?",
            "How can ecommerce firms ensure secure online transactions?",
            "What advantage does analyzing monthly order volume provide?",
            "Why is tracking top categories month by month helpful?",
            "What strategy can reduce order cancellations?",
            "Why do some customers abandon their carts online?",
            "How can personalized recommendations boost sales?",
            "Why is social media integration important in ecommerce?",
            "How do seasonal campaigns influence overall sales?",
            "Why do ecommerce companies invest in analytics dashboards?",
            "What does a high grand_total variance suggest?",
            "How can analyzing return rates improve profitability?",
            "Why is accurate inventory tracking critical for ecommerce?",
            "How does delivery time affect customer retention?",
            "Why should ecommerce firms analyze 'category_name_1' frequently?",
            "What role do festive discounts play in boosting sales?",
            "How can analyzing failed transactions help business improvement?",
            "Why are repeat buyers more valuable than new buyers?",
            "What is the importance of monitoring website traffic sources?",
            "How do customer retention programs impact ROI?",
            "Why is AI-based recommendation important in ecommerce?",
            "How can A/B testing help optimize ecommerce sales pages?",
            "What causes price fluctuations in ecommerce markets?",
            "How does the quality of product images affect conversion rates?",
            "Why is it vital to track customer churn?",
            "How does fast customer support influence buyer satisfaction?",
            "What can poor logistics performance lead to?",
            "Why is user-generated content beneficial for ecommerce?",
            "How do high-order frequency customers differ from occasional buyers?",
            "Why should ecommerce stores use email remarketing?",
            "How do referral programs help grow online businesses?",
            "Why are online ratings crucial for ecommerce credibility?",
            "What business insights can be gained from analyzing payment methods?",
            "How can analyzing daily order counts help in staffing decisions?",
            "Why do ecommerce businesses track regional sales distribution?",
            "What can long-term order trends reveal about market maturity?",
            "Why is cross-platform synchronization important for ecommerce?",
            "What does a sudden drop in sales indicate?",
            "Why do businesses monitor discount-to-sales ratios?",
            "How can delivery feedback loops improve future logistics?",
            "What does the presence of multiple payment gateways signify?",
            "Why is maintaining a positive BI Status important?",
            "How can trend forecasting improve stock management?",
            "Why should ecommerce sites track conversion funnel metrics?",
            "What role do affiliate codes play in ecommerce marketing?",
            "Why does analyzing the fiscal quarter help in business reporting?",
            "What advantage does real-time sales tracking provide?",
            "Which province shows the strongest engagement in online shopping activity?",
            "How does product pricing vary across categories?",
            "What role does Cash on Delivery play in Pakistani ecommerce?",
            "How can ecommerce businesses reduce cart abandonment?",
            "Which customer behavior patterns can be identified from repeated orders?",
            "What marketing strategy suits high-demand cities like Karachi and Lahore?",
            "How do seasonal trends influence sales volumes?",
            "What impact does mobile optimization have on ecommerce traffic?",
            "Which category benefits most from flash sales?",
            "What data points are key for understanding customer preferences?",
            "How can logistics performance be improved in ecommerce?",
            "Why are product reviews essential in ecommerce?",
            "How does discount depth affect sales velocity?",
            "Which product categories have the highest return rates?",
            "How can ecommerce firms increase repeat purchase rate?",
            "What role does social media marketing play in ecommerce success?",
            "How can ecommerce startups compete with larger platforms?",
            "What KPIs measure ecommerce performance effectively?",
            "How can AI improve ecommerce personalization?",
            "Why is customer data analysis critical for ecommerce growth?",
            "Which region exhibits the fastest growth in online retail adoption?",
            "How does delivery time influence customer satisfaction?",
            "What are the most common product search keywords in ecommerce?",
            "How can ecommerce platforms boost conversion rates?",
            "Which segment contributes the most to total sales value?",
            "How do ecommerce returns affect business profitability?",
            "What drives regional pricing variations in ecommerce?",
            "How can ecommerce companies attract first-time buyers?",
            "What is the role of customer segmentation in marketing?",
            "How can ecommerce businesses reduce delivery failures?",
            "What does the high mobile traffic indicate about ecommerce usage?",
            "Which time of year records the lowest ecommerce activity?",
            "How can product diversity influence cart value?",
            "What are common reasons for cart abandonment?",
            "How can ecommerce data be used for demand forecasting?",
            "Why is inventory management crucial for ecommerce?",
            "What is the relationship between price discounts and brand perception?",
            "Which customer demographics show highest online purchase activity?",
            "How can ecommerce platforms improve trust among first-time users?",
            "What is the effect of poor product imagery on conversions?",
            "Why are loyalty programs valuable in ecommerce?",
            "How can predictive analytics help ecommerce companies?",
            "What role do delivery charges play in purchase decisions?",
            "How does user experience design impact ecommerce success?",
            "What is the importance of secure payment gateways?",
            "How can cross-selling be effectively implemented?",
            "Why is customer feedback important for continuous improvement?",
            "What percentage of ecommerce transactions come from repeat buyers?",
            "How can email marketing enhance ecommerce engagement?",
            "What is the effect of offering installment payment options?",
            "Why should ecommerce platforms analyze regional language trends?",
            "How does customer satisfaction impact word-of-mouth marketing?",
            "What role do influencers play in ecommerce sales?",
            "How can ecommerce stores optimize return policies to minimize abuse?",
            "What data points are useful for identifying fraudulent orders?",
            "How can same-day delivery improve customer satisfaction?",
            "What is the role of chatbots in ecommerce support?",
            "Why should ecommerce platforms track customer churn?",
            "How does personalized product recommendation increase basket size?",
            "What’s the impact of delayed delivery on customer retention?",
            "Why is inventory accuracy important in multi-channel ecommerce?",
            "What metrics determine marketing campaign effectiveness?",
            "How does platform scalability affect ecommerce growth?",
            "How can ecommerce platforms strengthen customer loyalty in competitive markets?",
            "Why do some regions exhibit higher average order values?",
            "How can customer retention be measured effectively?",
            "What’s the role of product recommendations in upselling?",
            "How does delivery reliability affect brand reputation?",
            "What’s the impact of product availability on customer satisfaction?",
            "Why is product categorization important in ecommerce websites?",
            "How can ecommerce analytics improve pricing strategy?",
            "What’s the relationship between customer reviews and conversion rates?",
            "Why are abandoned carts valuable for remarketing?",
            "How does shipping cost transparency affect conversions?",
            "Which age group dominates online fashion purchases?",
            "How can data segmentation help tailor promotions?",
            "Why should ecommerce firms track delivery partner performance?",
            "How do user ratings influence new product launches?",
            "Why is localization critical in online retail marketing?",
            "How can return analytics reduce losses?",
            "What triggers impulse buying in ecommerce?",
            "How does product quality control impact brand trust?",
            "Why is customer onboarding important after the first purchase?",
            "What is the role of affiliate marketing in ecommerce growth?",
            "How can push notifications increase conversion rates?",
            "Why do customers prefer marketplaces over brand websites?",
            "How can predictive shipping improve user experience?",
            "Why do high-resolution images increase engagement?",
            "How can ecommerce firms use sentiment analysis?",
            "What’s the importance of conversion funnel analysis?",
            "Why should ecommerce data be visualized?",
            "How can ecommerce brands build trust through transparency?",
            "What’s the role of CRM tools in ecommerce?",
            "How can influencer campaigns be measured for ROI?",
            "Why are flash sales strategically important?",
            "How does data cleaning affect analytics accuracy?",
            "What’s the role of heatmaps in ecommerce UI design?",
            "Why should ecommerce sites use A/B testing?",
            "How can SEO improve ecommerce visibility?",
            "Why are omnichannel strategies gaining popularity?",
            "How does social proof influence online purchases?",
            "Why should ecommerce stores track bounce rates?",
            "How can dynamic pricing maximize revenue?",
            "What’s the impact of chatbot integration on service efficiency?",
            "Why do ecommerce businesses invest in app development?",
            "How can delivery feedback loops improve operations?",
            "What’s the advantage of offering order tracking?",
            "Why is product tagging useful in marketing automation?",
            "How can voice search optimization aid ecommerce?",
            "What are micro-moments in ecommerce?",
            "How does video marketing impact ecommerce engagement?",
            "Why should ecommerce sites enable guest checkout?",
            "How can post-purchase emails improve retention?",
            "Why do ecommerce firms track average session duration?",
            "How does mobile app UX differ from web UX in ecommerce?",
            "Why are repeat buyers more profitable than new ones?",
            "How can customer personas guide marketing strategy?",
            "What’s the value of tracking exit pages?",
            "Why are data dashboards essential for ecommerce managers?",
            "How does price anchoring influence customer perception?",
            "Why are sustainability practices relevant in ecommerce?",
            "How can sentiment tracking shape product development?",
            "Why should ecommerce brands monitor competitor pricing daily?",
            "How does personalized homepage content affect engagement?",
            "Why is fraud prevention crucial in COD orders?",
            "How can ecommerce companies manage peak-season demand?",
            "Why do customers value live chat over email support?",
            "How can data-driven personalization improve ROI?",
            "Why is multivariate testing more effective than A/B testing?",
            "What are the benefits of subscription-based ecommerce models?",
            "Why should ecommerce firms maintain backup payment gateways?",
            "How does website speed affect SEO and conversions?",
            "Why are abandoned-cart reminders effective?",
            "How can ecommerce firms measure customer advocacy?",
            "What’s the importance of clear product descriptions?",
            "Why do free returns encourage higher purchase confidence?",
            "How can gamification enhance customer engagement?",
            "Why should ecommerce brands invest in data governance?",
            "How can predictive churn models reduce attrition?",
            "Why are loyalty tiers effective in customer retention?",
            "How can ecommerce analytics optimize ad spend?",
            "What’s the impact of order tracking transparency?",
            "Why is social commerce growing rapidly?",
            "How can ecommerce stores use heatmap data to boost UX?",
            "Why are reviews with images more influential?",
            "How can AI chatbots improve lead qualification?",
            "Why do mobile push campaigns outperform emails?",
            "What are the benefits of offering easy EMI options?",
            "What are the most common challenges faced by ecommerce sellers in Pakistan?",
            "How can an ecommerce business optimize delivery logistics?",
            "Which data column helps identify returning customers in the dataset?",
            "What is the benefit of analyzing 'order_total' in ecommerce?",
            "What insights can be gained from tracking 'payment_method'?",
            "How does order frequency affect business forecasting?",
            "Why do ecommerce platforms promote prepaid payment methods?",
            "What metric best measures ecommerce growth?",
            "How do social media promotions affect ecommerce sales?",
            "What is an abandoned cart?",
            "Which strategy helps reduce cart abandonment?",
            "Why is order tracking important for customers?",
            "How can data analytics improve product pricing?",
            "What’s the importance of customer segmentation in ecommerce?",
            "Which column in the dataset helps analyze geographic trends?",
            "How can an ecommerce business predict high-demand products?",
            "Why do platforms offer cash-on-delivery?",
            "What are the risks of cash-on-delivery for sellers?",
            "How can ecommerce companies minimize returns?",
            "What does a high number of refunds indicate?",
            "How can customer feedback improve ecommerce strategy?",
            "What is cross-selling?",
            "What is up-selling?",
            "Why do ecommerce platforms track page views?",
            "What is the significance of conversion rate?",
            "How can machine learning improve ecommerce recommendations?",
            "What’s the purpose of a chatbot in ecommerce?",
            "How can ecommerce data predict seasonal demand?",
            "Why are product reviews critical for online sales?",
            "How can ecommerce businesses use predictive analytics?",
            "What’s the benefit of integrating CRM in ecommerce?",
            "How can A/B testing improve website performance?",
            "What is average order value (AOV)?",
            "Why do ecommerce platforms offer loyalty programs?",
            "What is customer churn?",
            "How can churn prediction help ecommerce platforms?",
            "What is dynamic pricing?",
            "Why is user experience (UX) design important in ecommerce?",
            "What’s the role of SEO in ecommerce?",
            "How can ecommerce businesses reduce bounce rate?",
            "What are KPIs in ecommerce?",
            "How can ecommerce companies use sentiment analysis?",
            "What is ROAS in digital marketing?",
            "How does free shipping affect conversions?",
            "Why is inventory forecasting crucial?",
            "What data point reflects delivery reliability?",
            "How can ecommerce firms use cohort analysis?",
            "Why should ecommerce companies track return reasons?",
            "What is the importance of mobile responsiveness?",
            "How can ecommerce platforms leverage influencer marketing?",
            "What is affiliate marketing in ecommerce?",
            "What insights can be derived from delivery time analysis?",
            "Why is customer lifetime value (CLV) significant?",
            "How can personalization boost ecommerce sales?",
            "What role does data visualization play in ecommerce analytics?",
            "How can AI improve demand forecasting?",
            "Why do ecommerce firms use recommendation engines?",
            "How can ecommerce platforms manage fraud risk?",
            "What is omnichannel retailing?",
            "What are key success factors for ecommerce startups?",
            "Why is product categorization vital?",
            "What insight does high cart abandonment rate give?",
            "How does customer feedback improve product development?",
            "Why should ecommerce firms analyze return frequency?",
            "What is the benefit of using dashboards in ecommerce analytics?",
            "How can an ecommerce business leverage big data?",
            "What’s the role of APIs in ecommerce systems?",
            "Why is real-time inventory tracking important?",
            "What do payment failure rates indicate?",
            "Why do ecommerce firms analyze delivery feedback?",
            "What’s the impact of festive sales on ecommerce?",
            "How can ecommerce platforms optimize advertising spend?",
            "What’s the advantage of data-driven decision-making?",
            "Why is checkout simplicity crucial?",
            "How can ecommerce improve after-sales support?",
            "What is the significance of tracking order cancellations?",
            "Why do ecommerce platforms use analytics dashboards?",
            "How can ecommerce companies benefit from heatmaps?",
            "What’s the value of repeat purchase rate metric?",
            "How can ecommerce firms use sentiment analysis of reviews?",
            "Why should ecommerce companies analyze search keywords?",
            "What insight can be derived from peak purchase times?",
            "Why is multilingual support important in ecommerce?",
            "What’s the role of push notifications in ecommerce?",
            "How can customer loyalty be increased?",
            "What’s the impact of delivery time on reviews?",
            "Why should ecommerce analyze profit margin by category?",
            "What’s the role of AI chatbots in ecommerce?",
            "How can predictive analytics reduce stockouts?",
            "Why do ecommerce firms track repeat visit frequency?",
            "What is NPS (Net Promoter Score)?",
            "Why are customer demographics important?",
            "How can ecommerce analyze product performance?",
            "What’s the significance of tracking failed deliveries?",
            "Why should ecommerce firms monitor refund rates?",
            "What data points help measure operational efficiency?",
            "How does image quality affect ecommerce sales?",
            "Why is secure checkout important?",
            "What’s the advantage of integrating social proof?",
            "How can ecommerce firms analyze supplier performance?",
            "What is customer retention rate?",
            "Why is personalization key in ecommerce marketing?",
            "How can ecommerce companies optimize return logistics?",
            "What’s the importance of trust badges on product pages?",
            "How does order tracking transparency affect retention?",
            "Why is AI essential for product recommendations?",
            "What does high customer acquisition cost indicate?",
            "How can email automation support ecommerce?",
            "What insight does low conversion rate provide?",
            "Why is feedback analysis important?",
            "How can ecommerce platforms enhance checkout speed?",
            "Why do ecommerce platforms track user session time?",
            "How can cart analytics improve conversions?",
            "What’s the role of feedback loops in ecommerce?",
            "How can ecommerce businesses benefit from referral programs?",
            "Why should ecommerce websites use HTTPS?",
            "What is a product funnel in ecommerce?",
            "Why do ecommerce businesses analyze click-through rates?",
            "How can social media ads increase ecommerce revenue?",
            "Why are chatbots preferred for customer support?",
            "How can ecommerce platforms monitor fraud prevention?",
            "What’s the importance of multi-channel selling?",
            "How can customer segmentation improve campaigns?",
            "Why should ecommerce platforms track wishlists?",
            "How can ecommerce platforms enhance image SEO?",
            "What is a customer journey map?",
            "Why is quick load time crucial for ecommerce websites?",
            "What is the purpose of website heatmaps?",
            "How can ecommerce use customer cohorts?",
            "Why are metrics like CAC important?",
            "How can ecommerce platforms predict future revenue?",
            "Why should ecommerce analyze product page exits?",
            "How can AI improve delivery route optimization?",
            "What’s the impact of customer reviews on conversion?",
            "Why is UX consistency important?",
            "How can ecommerce utilize real-time chat data?",
            "Why are loyalty tiers effective in ecommerce?",
            "What is basket analysis?",
            "How can ecommerce leverage Google Analytics?",
            "Why should ecommerce track session-to-order ratio?",
            "What’s the benefit of responsive email templates?",
            "How can predictive modeling support inventory management?",
            "Why do ecommerce firms track add-to-cart rate?",
            "What’s the value of customer heat scores?",
            "How can ecommerce optimize homepage layout?",
            "Why do ecommerce companies invest in content marketing?",
            "How can gamification improve ecommerce engagement?",
            "Why are trust signals essential in ecommerce design?",
            "What is customer advocacy?",
            "How can ecommerce businesses reduce bounce rate?",
            "Why are post-purchase emails effective?",
            "How can data clustering help in ecommerce?",
            "What is conversion funnel optimization?",
            "Why is a flexible return policy beneficial?",
            "How can ecommerce use data dashboards?",
            "What’s the importance of responsive design?",
            "Why is remarketing effective for ecommerce?",
            "What does a high bounce rate indicate?",
            "How can predictive analytics improve marketing ROI?",
            "Why is data-driven personalization valuable?",
            "What is churn analysis?",
            "Why is real-time order tracking essential?",
            "How can ecommerce firms optimize page SEO?",
            "Why do ecommerce platforms offer guest checkout?",
            "What is a user retention strategy?",
            "Why should ecommerce platforms automate email campaigns?",
            "How can ecommerce use behavioral data?",
            "What is a high-value customer segment?",
            "Why should ecommerce platforms use analytics APIs?",
            "How can user reviews improve SEO?",
            "Why is cross-device tracking important?",
            "How can AI improve ecommerce chatbots?",
            "Why do ecommerce firms use push notifications?",
            "What’s the value of multivariate testing?",
            "Why is customer journey tracking critical?",
            "How can machine learning optimize pricing?",
            "Why are voice searches becoming important?",
            "What is SKU optimization?",
            "Why do ecommerce firms track repeat order frequency?",
            "What is a conversion attribution model?",
            "How can ecommerce platforms improve accessibility?",
            "Why is trust important in digital transactions?",
            "What’s the purpose of email segmentation?",
            "How can ecommerce firms track fulfillment accuracy?",
            "Why is predictive lead scoring valuable?",
            "What’s the benefit of an integrated CRM?",
            "How does customer education affect ecommerce?",
            "Why should ecommerce analyze product availability?",
            "How can feedback loops improve UX?",
            "What’s the importance of multilingual chatbots?",
            "Why is API integration essential for scalability?",
            "What’s the value of lifetime customer tracking?",
            "Why do ecommerce platforms offer installment options?",
            "What is predictive customer support?",
            "Why should ecommerce platforms track ROI by campaign?",
            "How can ecommerce optimize product discovery?",
            "What is the impact of stock availability on trust?",
            "Why should ecommerce firms track cart recovery rate?",
            "What’s the benefit of data retention policies?",
            "Why is category-level profit analysis useful?",
            "How can ecommerce firms reduce refund processing time?",
            "What is predictive recommendation modeling?",
            "Why is local language marketing effective?",
            "How can ecommerce improve response time to inquiries?",
            "What’s the role of voice-enabled shopping?",
            "Why should ecommerce track social engagement?",
            "What’s the benefit of automating warehouse operations?",
            "Why is uptime monitoring essential for ecommerce?",
            "How can ecommerce optimize search functionality?",
            "Why do ecommerce platforms need backup payment gateways?",
            "What’s the importance of tracking repeat traffic?",
            "How can ecommerce analyze competitor pricing?",
            "Why is post-purchase follow-up valuable?",
            "How can ecommerce platforms use AI for returns prediction?",
            "What is inventory turnover ratio?",
            "Why should ecommerce track product view-to-purchase ratio?",
            "What’s the purpose of business intelligence dashboards?",
            "Why do ecommerce platforms use heatmap analytics?",
            "How can ecommerce predict new customer acquisition?",
            "What’s the role of augmented reality in ecommerce?",
            "Why should ecommerce firms use warehouse management systems?",
            "How can machine learning detect ecommerce fraud?",
            "Why is cross-border ecommerce growing?",
            "How can ecommerce firms analyze campaign success?",
            "Why are KPIs important in ecommerce management?",
            "What’s the future of ecommerce in Pakistan?",
            "How can SMEs leverage ecommerce analytics?",
            "Why is customer-centric strategy essential?"
        ],
        "follow_ups": [],
        "cross_questions": [],
        "answers": {
            "insight_1": "The most popular categories include Mobiles & Tablets, Men's Fashion, Women's Fashion, Appliances, and Superstore.",
            "insight_2": "The average price across products is approximately PKR 6350.49.",
            "insight_3": "The most common payment methods are COD, Payaxis, Easypay, JazzWallet, and Easypay Voucher.",
            "insight_4": "A high average order total (around PKR 8532.53) indicates strong purchase confidence and high-value transactions.",
            "insight_5": "By offering discounts, improving product visibility, and using targeted digital marketing in the Mobiles & Tablets category.",
            "insight_6": "The month with the highest sales typically occurs around festive seasons, where demand increases sharply.",
            "insight_7": "Because many customers prefer paying after receiving the product, reflecting trust-building behavior in ecommerce.",
            "insight_8": "The grand total depends on product price, quantity ordered, and discounts applied.",
            "insight_9": "Larger discounts increase order frequency and encourage customers to explore new product categories.",
            "insight_10": "Categories like Superstore, Mobiles & Tablets, and Men's Fashion tend to have higher order quantities.",
            "insight_11": "Possible causes include customer change of mind, product unavailability, or payment verification issues.",
            "insight_12": "It indicates whether an order was completed, canceled, pending, or refunded.",
            "insight_13": "Because of a wide variety of styles, frequent new arrivals, and strong interest in apparel shopping online.",
            "insight_14": "Offering bundle discounts, influencer marketing, and customer loyalty programs.",
            "insight_15": "Discounts, product necessity, and customer trust in the brand influence the quantity ordered.",
            "insight_16": "It helps identify seasonal trends, daily sales patterns, and time-based performance metrics.",
            "insight_17": "These columns help analyze growth trends and seasonal variations in sales performance.",
            "insight_18": "It reflects customer satisfaction, brand loyalty, and long-term profitability.",
            "insight_19": "They significantly increase traffic and conversion rates, especially when combined with social media campaigns.",
            "insight_20": "Fast and reliable delivery improves trust and repeat purchases, which are crucial for ecommerce growth.",
            "insight_21": "Because they trust the platform and prefer convenience over handling cash.",
            "insight_22": "It reflects total revenue generated per order, useful for identifying high-value customers.",
            "insight_23": "Karachi, as the country's largest economic hub, typically leads in online shopping volume.",
            "insight_24": "Lower prices tend to increase order quantity, while higher prices may reduce it unless the brand is strong.",
            "insight_25": "By analyzing customer preferences and targeting ads toward high-performing categories.",
            "insight_26": "It helps track affiliate or agent-based sales performance.",
            "insight_27": "It helps reduce cancellations and ensures timely resolution of order issues.",
            "insight_28": "Positive reviews increase trust, improve search rankings, and lead to higher conversion rates.",
            "insight_29": "Possible causes include off-season demand, reduced promotions, or economic slowdowns.",
            "insight_30": "It allows businesses to allocate resources to high-performing segments.",
            "insight_31": "Frequent stockouts frustrate customers and push them to competitors.",
            "insight_32": "By improving product descriptions, ensuring quality checks, and offering easy return policies.",
            "insight_33": "Because price sensitivity is high, and small discounts can lead to significant sales volume increases.",
            "insight_34": "Showcasing style guides, influencer partnerships, and targeted email marketing.",
            "insight_35": "Because of varying styles, sizes, colors, and seasonal trends.",
            "insight_36": "It helps track customer lifetime value and retention trends.",
            "insight_37": "By analyzing purchase frequency, average order value, and engagement levels.",
            "insight_38": "It allows for better financial planning and yearly performance analysis.",
            "insight_39": "Events like flash sales, national holidays, or promotional campaigns.",
            "insight_40": "Convenient and secure payment options encourage repeat purchases.",
            "insight_41": "Product damage, incorrect size, or late delivery.",
            "insight_42": "By tailoring offers and messages according to specific customer groups.",
            "insight_43": "It indicates overall profitability and helps in upselling or cross-selling strategies.",
            "insight_44": "It shows which products are frequently purchased and helps forecast inventory needs.",
            "insight_45": "Because it enables precise forecasting, better inventory management, and targeted marketing.",
            "insight_46": "By launching targeted discounts, loyalty programs, and new product lines.",
            "insight_47": "It indicates potential issues with customer trust, delivery, or product presentation.",
            "insight_48": "Different age groups and regions have varying product preferences and spending capacity.",
            "insight_49": "Because a large portion of customers in Pakistan shop using smartphones.",
            "insight_50": "It helps identify seasonal peaks and plan marketing budgets accordingly.",
            "insight_51": "To assess product positioning and profitability across categories.",
            "insight_52": "By revealing pain points in the buying process, delivery, or product quality.",
            "insight_53": "Because it enables targeted customer acquisition at a lower cost than traditional media.",
            "insight_54": "Growing trust in digital transactions and better access to fintech solutions.",
            "insight_55": "High return risk, operational delays, and dependency on delivery agents.",
            "insight_56": "By using SSL encryption, verified gateways, and multi-factor authentication.",
            "insight_57": "It helps predict demand cycles and manage inventory more efficiently.",
            "insight_58": "To identify emerging trends and shifting customer interests.",
            "insight_59": "Improving delivery accuracy and real-time tracking communication.",
            "insight_60": "Because of unexpected costs, long checkout processes, or technical issues.",
            "insight_61": "They increase engagement and make customers discover relevant products easily.",
            "insight_62": "Because it drives traffic, enhances trust, and enables influencer collaborations.",
            "insight_63": "They boost brand visibility and significantly drive short-term revenue growth.",
            "insight_64": "To track performance KPIs and make data-backed business decisions.",
            "insight_65": "That product diversity and customer purchasing power vary widely.",
            "insight_66": "By identifying products or sellers with consistent quality issues.",
            "insight_67": "It prevents stockouts, overstocking, and customer dissatisfaction.",
            "insight_68": "Faster deliveries improve satisfaction and loyalty rates.",
            "insight_69": "To monitor product mix and identify high-growth areas.",
            "insight_70": "They create urgency and attract price-sensitive shoppers.",
            "insight_71": "By identifying payment gateway issues or user experience bottlenecks.",
            "insight_72": "Because they have higher lifetime value and lower acquisition cost.",
            "insight_73": "It helps identify the most effective marketing channels for sales.",
            "insight_74": "They reduce churn and increase repeat purchase rates over time.",
            "insight_75": "Because it personalizes the shopping journey and boosts conversion rates.",
            "insight_76": "By showing which design or messaging performs better in converting visitors.",
            "insight_77": "Changes in demand, promotions, and competition levels.",
            "insight_78": "High-quality visuals increase customer confidence and reduce returns.",
            "insight_79": "To understand why users stop purchasing and to improve engagement.",
            "insight_80": "Quick responses resolve issues and encourage repeat shopping.",
            "insight_81": "Increased cancellations, late deliveries, and poor customer feedback.",
            "insight_82": "It builds trust and provides authentic product validation.",
            "insight_83": "They exhibit brand loyalty, higher spending, and positive word-of-mouth influence.",
            "insight_84": "To re-engage abandoned cart users and boost conversion rates.",
            "insight_85": "They leverage existing customers to attract new ones through incentives.",
            "insight_86": "Because shoppers rely on reviews before making purchase decisions.",
            "insight_87": "They reveal customer preferences and technology adoption trends.",
            "insight_88": "It assists in managing workforce requirements during high-demand periods.",
            "insight_89": "To plan localized marketing campaigns and warehouse operations.",
            "insight_90": "They indicate whether the market is expanding, stabilizing, or declining.",
            "insight_91": "It ensures consistent customer experience across mobile and web interfaces.",
            "insight_92": "Possible website issues, competitor promotions, or customer dissatisfaction.",
            "insight_93": "To maintain profitability while ensuring attractive offers.",
            "insight_94": "They identify bottlenecks and enable better routing and time predictions.",
            "insight_95": "Flexibility for users and broader market accessibility.",
            "insight_96": "It indicates successful order processing and revenue recognition consistency.",
            "insight_97": "By predicting high-demand products and avoiding overstock situations.",
            "insight_98": "To pinpoint where customers drop off during the shopping process.",
            "insight_99": "They help measure influencer and affiliate campaign effectiveness.",
            "insight_100": "It aligns marketing and financial evaluations with quarterly targets.",
            "insight_101": "It helps businesses respond quickly to spikes or declines in demand.",
            "insight_102": "Punjab leads in ecommerce engagement, followed by Sindh due to major cities like Karachi and Lahore.",
            "insight_103": "High-value electronics and appliances raise the average price, while fashion and grocery items stay in the mid to low range.",
            "insight_104": "COD dominates transactions, highlighting customer preference for trust and post-delivery payment assurance.",
            "insight_105": "Simplify checkout, offer multiple payment options, provide delivery estimates, and send timely reminders.",
            "insight_106": "Repeated orders suggest loyalty and satisfaction, often linked to reliable delivery and product quality.",
            "insight_107": "Targeted social media ads and same-day delivery offers work effectively in densely populated urban centers.",
            "insight_108": "Sales peak during Ramadan, Eid, and Independence Day promotions, with heavy discounts boosting conversions.",
            "insight_109": "Over 70% of users shop via smartphones; mobile-friendly design directly improves conversion rates.",
            "insight_110": "Electronics, particularly smartphones and accessories, see sharp spikes during flash sale events.",
            "insight_111": "Purchase history, browsing time, location, and price sensitivity are critical indicators.",
            "insight_112": "Partner with multiple couriers, use route optimization, and provide live tracking to customers.",
            "insight_113": "Reviews build trust, reduce return rates, and influence up to 80% of purchase decisions.",
            "insight_114": "Moderate discounts (10-20%) maintain margins while driving sustainable order volumes.",
            "insight_115": "Clothing and fashion accessories often have higher returns due to size or color mismatches.",
            "insight_116": "Implement loyalty programs, personalized recommendations, and re-engagement emails.",
            "insight_117": "Platforms like Facebook, Instagram, and TikTok drive brand visibility and conversion through targeted campaigns.",
            "insight_118": "Focus on niche products, customer service excellence, and hyperlocal logistics partnerships.",
            "insight_119": "Conversion rate, average order value, customer acquisition cost, and retention rate are key.",
            "insight_120": "AI algorithms recommend products, predict churn, and optimize pricing dynamically.",
            "insight_121": "It reveals spending habits, preferred categories, and helps forecast demand patterns.",
            "insight_122": "Southern Punjab and interior Sindh show rapid adoption as internet access expands.",
            "insight_123": "Shorter delivery times directly correlate with higher satisfaction and repeat purchase likelihood.",
            "insight_124": "Terms like 'mobile', 'dress', 'shoes', and 'sale' dominate customer search patterns.",
            "insight_125": "Enhance product visuals, simplify checkout, and use urgency tactics like limited-time offers.",
            "insight_126": "Electronics and mobile accessories typically contribute the highest revenue share.",
            "insight_127": "High return rates increase logistics costs and erode margins if not managed efficiently.",
            "insight_128": "Shipping distance, local taxes, and competition intensity cause price differences.",
            "insight_129": "Offer sign-up discounts, simple onboarding, and highlight popular products with reviews.",
            "insight_130": "Segmentation enables personalized campaigns for demographics, purchase behavior, and region.",
            "insight_131": "Verify customer addresses, use confirmation calls, and optimize last-mile logistics.",
            "insight_132": "It shows Pakistan’s shift toward mobile-first shopping behavior driven by affordable smartphones.",
            "insight_133": "Sales dip during mid-year months outside major shopping festivals or promotions.",
            "insight_134": "A broader catalog increases cross-selling opportunities, raising average order values.",
            "insight_135": "Unexpected shipping costs, lengthy checkout, and lack of preferred payment options.",
            "insight_136": "Past order volumes, seasonal peaks, and price trends help build predictive models.",
            "insight_137": "It ensures product availability, reduces overstocking, and lowers holding costs.",
            "insight_138": "Frequent deep discounts can reduce perceived brand value if not strategically applied.",
            "insight_139": "Urban youth and middle-income professionals aged 20-35 are the most active shoppers.",
            "insight_140": "Provide clear return policies, customer reviews, and COD options for assurance.",
            "insight_141": "Low-quality images significantly decrease click-through and purchase rates.",
            "insight_142": "They increase retention, repeat purchase rates, and long-term customer lifetime value.",
            "insight_143": "It anticipates customer needs and optimizes stock levels and marketing spend.",
            "insight_144": "Free or low delivery charges improve checkout conversion by 15-25%.",
            "insight_145": "Intuitive navigation, fast loading pages, and responsive design improve user engagement.",
            "insight_146": "They protect sensitive data, build user trust, and reduce cart abandonment due to security fears.",
            "insight_147": "Use 'Frequently Bought Together' and 'Related Products' sections on product pages.",
            "insight_148": "It highlights product or delivery issues, enabling faster corrective actions.",
            "insight_149": "Typically around 40–50%, depending on loyalty initiatives and service quality.",
            "insight_150": "Personalized recommendations and discount reminders drive re-engagement and conversions.",
            "insight_151": "It increases affordability and boosts sales of high-value items like appliances and mobiles.",
            "insight_152": "Localized marketing in Urdu or regional dialects increases relatability and reach.",
            "insight_153": "Satisfied customers become advocates, generating organic traffic through referrals.",
            "insight_154": "Influencer endorsements boost credibility, especially in beauty and fashion segments.",
            "insight_155": "Set clear conditions, time limits, and track return frequency by customer ID.",
            "insight_156": "Unusual order quantities, mismatched addresses, and repeated failed payments are key signals.",
            "insight_157": "It fulfills urgency needs and enhances convenience for high-value customers.",
            "insight_158": "Chatbots handle FAQs, assist in order tracking, and provide 24/7 support cost-effectively.",
            "insight_159": "Monitoring churn helps identify at-risk customers and design retention strategies.",
            "insight_160": "Relevant suggestions encourage customers to buy complementary items, boosting revenue.",
            "insight_161": "Repeated delays lead to poor reviews and lower repeat order probability.",
            "insight_162": "Accurate stock data prevents overselling and ensures timely order fulfillment.",
            "insight_163": "Click-through rate, conversion rate, ROI, and customer acquisition cost are vital metrics.",
            "insight_164": "Scalable systems handle traffic surges during sales without performance degradation.",
            "insight_165": "By offering exclusive rewards, referral bonuses, and personalized experiences for loyal shoppers.",
            "insight_166": "Affluent urban areas and tech-savvy populations tend to purchase higher-priced electronics and branded goods.",
            "insight_167": "Through metrics like repeat purchase rate, churn rate, and customer lifetime value (CLV).",
            "insight_168": "They expose buyers to premium versions or complementary items, boosting total order value.",
            "insight_169": "Consistent on-time delivery strengthens trust and directly influences repeat orders.",
            "insight_170": "Stock-outs frustrate customers and push them toward competitors with better inventory control.",
            "insight_171": "It improves discoverability, navigation, and search accuracy, enhancing user experience.",
            "insight_172": "By tracking price elasticity, competitor pricing, and demand to adjust prices dynamically.",
            "insight_173": "Products with multiple positive reviews enjoy up to 30–40% higher conversion rates.",
            "insight_174": "They indicate strong intent, and retargeting these users often converts at higher rates.",
            "insight_175": "Clear upfront shipping charges prevent last-minute drop-offs at checkout.",
            "insight_176": "Individuals aged 18–30 are the most active online fashion shoppers.",
            "insight_177": "It allows different discounts for first-time users, loyal customers, and high-value segments.",
            "insight_178": "Evaluating on-time rates and complaint frequency ensures service quality consistency.",
            "insight_179": "Positive early ratings accelerate adoption, while poor ones can stall growth.",
            "insight_180": "Localized pricing, language, and holidays make campaigns more relevant to customers.",
            "insight_181": "Identifying high-return SKUs and root causes helps optimize product descriptions and QC.",
            "insight_182": "Limited-time offers, scarcity cues, and personalized recommendations drive impulse purchases.",
            "insight_183": "Reliable quality reduces refunds, builds confidence, and improves long-term retention.",
            "insight_184": "Guided onboarding emails and tutorials encourage app installs and repeated engagement.",
            "insight_185": "Affiliates extend brand reach and drive traffic through performance-based partnerships.",
            "insight_186": "Timely personalized alerts about offers or restocks prompt quick buying decisions.",
            "insight_187": "Marketplaces offer variety, trust, and convenience with consolidated logistics and reviews.",
            "insight_188": "Forecasting demand allows pre-positioning inventory near likely buyers for faster delivery.",
            "insight_189": "They provide detail confidence and reduce uncertainty, boosting add-to-cart rates.",
            "insight_190": "Analyzing reviews helps identify customer pain points and product improvement areas.",
            "insight_191": "It identifies where customers drop off and guides UI or marketing optimization.",
            "insight_192": "Visualization simplifies complex KPIs, making trend spotting and decisions faster.",
            "insight_193": "By showing authentic reviews, clear pricing, and verified seller badges.",
            "insight_194": "They manage customer interactions, automate marketing, and track satisfaction metrics.",
            "insight_195": "Track referral codes, UTM links, and sales conversions from influencer content.",
            "insight_196": "They create urgency, clear inventory, and attract new customers through hype.",
            "insight_197": "Removing duplicates and inconsistencies ensures reliable insights and decisions.",
            "insight_198": "They reveal where users click or pause, guiding interface optimization.",
            "insight_199": "Testing variations identifies which design or copy yields better engagement.",
            "insight_200": "Optimizing product titles, descriptions, and site speed boosts organic rankings.",
            "insight_201": "Customers expect seamless transitions between web, mobile, and in-store experiences.",
            "insight_202": "Seeing others’ purchases or reviews builds trust and validates buying decisions.",
            "insight_203": "High bounce rates signal poor user experience or irrelevant search targeting.",
            "insight_204": "Adjusting prices in real time based on demand optimizes profit margins.",
            "insight_205": "It reduces response time, handles routine queries, and cuts support costs.",
            "insight_206": "Apps offer smoother UX, push notifications, and loyalty integration for retention.",
            "insight_207": "Collecting courier ratings helps identify logistics partners that need improvement.",
            "insight_208": "Transparency reduces customer anxiety and support inquiries about delivery status.",
            "insight_209": "Tags enable personalized recommendations and segment-specific promotions.",
            "insight_210": "As smart assistants grow, optimizing for conversational queries captures new traffic.",
            "insight_211": "Short decision windows where customers expect instant, context-relevant information.",
            "insight_212": "Videos explain features better, increase time on site, and improve conversion.",
            "insight_213": "It removes registration friction, raising conversion among first-time users.",
            "insight_214": "They encourage reviews, cross-selling, and reinforce positive purchase experiences.",
            "insight_215": "Longer sessions often indicate better engagement and higher conversion likelihood.",
            "insight_216": "Mobile UX emphasizes speed, thumb-friendly design, and minimal input fields.",
            "insight_217": "They have lower acquisition costs and higher lifetime value over time.",
            "insight_218": "Personas clarify motivations and preferences, improving campaign relevance.",
            "insight_219": "It helps pinpoint where customers lose interest before completing purchases.",
            "insight_220": "They consolidate KPIs, speeding decision-making and cross-team communication.",
            "insight_221": "Showing original vs discounted prices makes deals appear more attractive.",
            "insight_222": "Eco-friendly packaging and carbon-neutral shipping attract conscious consumers.",
            "insight_223": "Analyzing review tone highlights strengths and weaknesses for iteration.",
            "insight_224": "Rapid changes in competitor offers can shift customer choices instantly.",
            "insight_225": "Tailored layouts increase click-through and conversion compared to static pages.",
            "insight_226": "Unverified addresses and fake orders cause unnecessary shipping costs.",
            "insight_227": "Scale server capacity, pre-stock bestsellers, and streamline courier coordination.",
            "insight_228": "Instant assistance builds confidence and reduces purchase hesitation.",
            "insight_229": "Using behavior insights for targeted messaging increases relevance and sales.",
            "insight_230": "It evaluates several variables simultaneously for deeper optimization insights.",
            "insight_231": "They ensure recurring revenue and stronger long-term customer relationships.",
            "insight_232": "Backup gateways prevent transaction failures and reduce lost sales opportunities.",
            "insight_233": "Faster sites rank better on search engines and lower bounce rates significantly.",
            "insight_234": "They reignite interest and convert hesitant shoppers within 24–48 hours.",
            "insight_235": "Use Net Promoter Score (NPS) and referral rate to gauge advocacy strength.",
            "insight_236": "They reduce pre-purchase confusion and lower post-purchase return rates.",
            "insight_237": "They eliminate perceived risk and increase average basket sizes.",
            "insight_238": "Reward systems, leaderboards, and progress badges motivate frequent interaction.",
            "insight_239": "Structured policies ensure privacy compliance and reliable analytics quality.",
            "insight_240": "By flagging at-risk users and triggering timely re-engagement campaigns.",
            "insight_241": "Tiered rewards motivate customers to spend more to reach higher benefits.",
            "insight_242": "Attribution tracking identifies the best-performing channels for reallocation.",
            "insight_243": "Customers appreciate updates, reducing support queries and boosting trust.",
            "insight_244": "Integrated shopping features on social media simplify discovery-to-purchase journeys.",
            "insight_245": "By redesigning low-engagement sections and improving CTA visibility.",
            "insight_246": "They appear authentic, giving visual assurance about product quality.",
            "insight_247": "By instantly filtering serious buyers through intelligent questioning.",
            "insight_248": "They reach users instantly and enjoy higher open and click-through rates.",
            "insight_249": "They drive sales of premium items while maintaining affordability for customers.",
            "insight_250": "Challenges include payment trust issues, delivery delays, and limited access to digital marketing expertise.",
            "insight_251": "By partnering with multiple courier services, using route optimization, and monitoring delivery KPIs.",
            "insight_252": "Customer ID or email identifiers can be used to track repeat customers.",
            "insight_253": "It helps determine high-value customers and average order sizes.",
            "insight_254": "It reveals customer trust preferences and helps optimize available payment options.",
            "insight_255": "Higher frequency indicates customer retention and supports better sales prediction.",
            "insight_256": "To reduce cash-handling risks and improve payment efficiency.",
            "insight_257": "Year-over-year revenue growth and unique customer count are key metrics.",
            "insight_258": "They increase traffic and conversions by enhancing product visibility and engagement.",
            "insight_259": "It occurs when a customer adds items to their cart but doesn’t complete the purchase.",
            "insight_260": "Send reminder emails and offer limited-time discounts for incomplete purchases.",
            "insight_261": "It builds transparency and increases trust by allowing customers to monitor their shipment.",
            "insight_262": "By comparing sales data, seasonality, and competitor pricing trends.",
            "insight_263": "It allows targeted marketing and personalized recommendations.",
            "insight_264": "The ‘city’ or ‘region’ column indicates where most orders originate.",
            "insight_265": "By analyzing past sales, search trends, and inventory turnover.",
            "insight_266": "Because many customers in Pakistan prefer paying after product inspection.",
            "insight_267": "Higher return rates and potential payment default or delivery refusal.",
            "insight_268": "By providing accurate product descriptions, images, and reliable delivery.",
            "insight_269": "Possible issues in quality control, customer satisfaction, or delivery process.",
            "insight_270": "By revealing pain points and guiding improvements in service and product quality.",
            "insight_271": "Recommending complementary products to customers during checkout.",
            "insight_272": "Encouraging customers to purchase a higher-end or upgraded version of a product.",
            "insight_273": "To measure customer interest and optimize product listings.",
            "insight_274": "It measures how many visitors make a purchase after viewing products.",
            "insight_275": "By analyzing customer behavior to suggest relevant products dynamically.",
            "insight_276": "To handle FAQs, guide users, and automate support 24/7.",
            "insight_277": "By identifying historical spikes in sales during specific months or holidays.",
            "insight_278": "They build credibility and influence purchasing decisions.",
            "insight_279": "To forecast demand, prevent stockouts, and optimize marketing campaigns.",
            "insight_280": "To track customer relationships and enhance personalized service.",
            "insight_281": "By comparing two versions of a webpage to see which performs better.",
            "insight_282": "A metric showing the average amount spent per order, useful for revenue analysis.",
            "insight_283": "To retain customers and encourage repeat purchases.",
            "insight_284": "When customers stop buying from a business, reducing retention rate.",
            "insight_285": "It identifies at-risk customers and enables retention strategies.",
            "insight_286": "Adjusting prices in real-time based on demand and competition.",
            "insight_287": "Because it affects navigation ease and purchase likelihood.",
            "insight_288": "It improves organic visibility and brings more potential buyers to the site.",
            "insight_289": "By improving page load time and enhancing product descriptions.",
            "insight_290": "Key Performance Indicators such as conversion rate, AOV, retention rate, and NPS.",
            "insight_291": "By analyzing customer reviews to gauge satisfaction levels.",
            "insight_292": "Return on Ad Spend — measures the effectiveness of advertising campaigns.",
            "insight_293": "It reduces purchase hesitation and increases order volume.",
            "insight_294": "It prevents stockouts and excess inventory, balancing operations.",
            "insight_295": "On-time delivery rate helps measure logistics efficiency.",
            "insight_296": "To study behavior patterns of customer groups over time.",
            "insight_297": "To identify product quality issues and reduce future returns.",
            "insight_298": "A mobile-friendly site ensures accessibility and better conversion on phones.",
            "insight_299": "By partnering with influencers to promote products and reach new audiences.",
            "insight_300": "A commission-based system where affiliates promote products for a reward.",
            "insight_301": "It highlights courier performance and regional bottlenecks.",
            "insight_302": "It helps measure long-term profitability of each customer relationship.",
            "insight_303": "By tailoring offers and recommendations to individual user behavior.",
            "insight_304": "It helps managers interpret sales trends and make data-driven decisions.",
            "insight_305": "By analyzing historical patterns and external factors for accurate prediction.",
            "insight_306": "To increase cross-selling and improve customer experience.",
            "insight_307": "By monitoring transaction patterns and using machine learning for detection.",
            "insight_308": "An integrated approach combining online, offline, and mobile experiences.",
            "insight_309": "Strong logistics, trust, customer service, and marketing execution.",
            "insight_310": "It simplifies navigation and enhances search relevance.",
            "insight_311": "Possible issues with checkout process, pricing, or trust signals.",
            "insight_312": "It helps refine features based on user expectations.",
            "insight_313": "To identify unreliable suppliers and improve product quality.",
            "insight_314": "They provide real-time performance metrics for decision-makers.",
            "insight_315": "By identifying trends, predicting behavior, and optimizing operations.",
            "insight_316": "APIs integrate payment, logistics, and marketing tools seamlessly.",
            "insight_317": "It prevents overselling and maintains accurate stock levels.",
            "insight_318": "Technical or trust issues during checkout process.",
            "insight_319": "It reveals courier reliability and customer satisfaction.",
            "insight_320": "Festivals lead to surge in orders and marketing opportunities.",
            "insight_321": "By using ROI tracking and focusing on high-performing campaigns.",
            "insight_322": "It reduces guesswork and increases strategic accuracy.",
            "insight_323": "Complex checkouts cause drop-offs; simplicity boosts completion.",
            "insight_324": "By offering chatbots, quick refunds, and feedback systems.",
            "insight_325": "It identifies operational or customer experience problems.",
            "insight_326": "To monitor KPIs, track progress, and optimize campaigns.",
            "insight_327": "Heatmaps show user interaction zones on websites for UX improvement.",
            "insight_328": "It reflects customer loyalty and product satisfaction.",
            "insight_329": "To detect dissatisfaction trends and fix recurring product issues.",
            "insight_330": "It helps understand demand and optimize SEO efforts.",
            "insight_331": "Helps schedule ads and offers during high-traffic hours.",
            "insight_332": "To cater to diverse customers in multilingual regions like Pakistan.",
            "insight_333": "They increase engagement by reminding users of new offers.",
            "insight_334": "Through personalized discounts and reward programs.",
            "insight_335": "Faster delivery leads to higher satisfaction and better ratings.",
            "insight_336": "To focus marketing on high-margin items.",
            "insight_337": "They automate support, reduce costs, and increase responsiveness.",
            "insight_338": "By forecasting product demand and triggering timely restocks.",
            "insight_339": "It signals customer engagement and brand interest.",
            "insight_340": "A measure of customer loyalty based on willingness to recommend.",
            "insight_341": "They influence marketing segmentation and targeting accuracy.",
            "insight_342": "By comparing sales, returns, and ratings across categories.",
            "insight_343": "It highlights logistics inefficiencies and regional challenges.",
            "insight_344": "High refunds indicate dissatisfaction or order process errors.",
            "insight_345": "Fulfillment speed, order accuracy, and delivery success rate.",
            "insight_346": "High-quality images improve trust and conversion rate.",
            "insight_347": "It prevents fraud and builds customer trust.",
            "insight_348": "Social proof boosts credibility and influences buyers.",
            "insight_349": "By tracking defect rates and delivery times per supplier.",
            "insight_350": "The percentage of repeat customers over total unique buyers.",
            "insight_351": "It improves relevance and increases conversion likelihood.",
            "insight_352": "By automating return requests and partnering with reverse logistics firms.",
            "insight_353": "They reassure customers about security and authenticity.",
            "insight_354": "Customers with visibility into their orders are more likely to reorder.",
            "insight_355": "AI learns customer patterns to improve recommendation accuracy.",
            "insight_356": "Inefficient marketing or poor targeting strategies.",
            "insight_357": "It maintains engagement with product updates and offers.",
            "insight_358": "Issues with product pricing, trust signals, or UX design.",
            "insight_359": "It identifies recurring problems and improves service quality.",
            "insight_360": "By simplifying forms, enabling auto-fill, and supporting multiple payment gateways.",
            "insight_361": "It helps measure engagement and identify website usability issues.",
            "insight_362": "By identifying frequently abandoned products and optimizing pricing or promotions.",
            "insight_363": "They continuously improve customer experience through data-driven insights.",
            "insight_364": "Referral programs encourage customers to bring in new buyers at lower acquisition costs.",
            "insight_365": "It ensures data security and boosts customer trust during checkout.",
            "insight_366": "It represents the customer journey from discovery to purchase completion.",
            "insight_367": "To assess the effectiveness of marketing and product listing optimization.",
            "insight_368": "They drive traffic and boost visibility for promotions and new products.",
            "insight_369": "They provide instant responses, reduce workload, and enhance user experience.",
            "insight_370": "By tracking unusual purchase patterns and validating payment information.",
            "insight_371": "It diversifies revenue streams and reaches more customers through various platforms.",
            "insight_372": "It allows targeted communication and increases ROI on marketing spend.",
            "insight_373": "They indicate future purchase intent and can guide remarketing.",
            "insight_374": "By using descriptive filenames, alt tags, and compressed image formats.",
            "insight_375": "A visual representation of all touchpoints a customer has with a brand.",
            "insight_376": "Slow websites lead to drop-offs and reduced sales conversions.",
            "insight_377": "They show where users click most, guiding UI/UX improvements.",
            "insight_378": "To identify buying patterns among specific groups for personalized marketing.",
            "insight_379": "They measure customer acquisition cost, helping manage profitability.",
            "insight_380": "By analyzing trends in average order value and repeat purchase rate.",
            "insight_381": "To detect barriers preventing users from proceeding to checkout.",
            "insight_382": "AI analyzes traffic and geography to suggest the fastest delivery paths.",
            "insight_383": "Positive reviews significantly increase trust and purchase decisions.",
            "insight_384": "A consistent layout builds familiarity and simplifies navigation.",
            "insight_385": "To identify customer pain points and improve service scripts.",
            "insight_386": "They encourage higher spending to reach better reward levels.",
            "insight_387": "A data-mining technique used to find product purchase correlations.",
            "insight_388": "To track site traffic, user behavior, and conversion funnel performance.",
            "insight_389": "It measures how effectively visits are converted to actual purchases.",
            "insight_390": "They ensure marketing emails display correctly on all devices.",
            "insight_391": "It helps forecast future demand and optimize stock levels.",
            "insight_392": "It indicates customer intent and effectiveness of product presentation.",
            "insight_393": "They help prioritize high-value leads based on activity patterns.",
            "insight_394": "By highlighting top categories and offers to increase engagement.",
            "insight_395": "To educate customers and improve organic search visibility.",
            "insight_396": "By rewarding users with points or badges to encourage activity.",
            "insight_397": "They reduce perceived risk and increase transaction likelihood.",
            "insight_398": "When satisfied customers promote your brand through word of mouth.",
            "insight_399": "By improving design, relevancy, and website performance.",
            "insight_400": "They encourage feedback, repeat purchases, and referrals.",
            "insight_401": "By grouping similar customers for targeted promotions.",
            "insight_402": "The process of improving each stage from visit to purchase.",
            "insight_403": "It builds trust and increases customer satisfaction.",
            "insight_404": "To visualize KPIs and track real-time performance metrics.",
            "insight_405": "Ensures accessibility and usability on all screen sizes.",
            "insight_406": "It re-engages users who left without purchasing.",
            "insight_407": "That users are leaving early, possibly due to poor UX or relevance.",
            "insight_408": "By identifying high-potential leads and optimizing ad spend.",
            "insight_409": "It creates tailored experiences that boost customer loyalty.",
            "insight_410": "Identifying why customers stop purchasing to reduce future losses.",
            "insight_411": "It builds trust and transparency for customers.",
            "insight_412": "By using relevant keywords, metadata, and optimized URLs.",
            "insight_413": "To reduce friction and speed up the purchasing process.",
            "insight_414": "A plan focused on keeping existing customers engaged and active.",
            "insight_415": "It ensures timely communication without manual intervention.",
            "insight_416": "To predict purchase intent and customize recommendations.",
            "insight_417": "Customers contributing the most revenue or frequent purchases.",
            "insight_418": "To integrate real-time metrics into dashboards or reports.",
            "insight_419": "They generate fresh, keyword-rich content that boosts rankings.",
            "insight_420": "It identifies how customers interact across mobile and desktop.",
            "insight_421": "By learning context and offering intelligent, human-like responses.",
            "insight_422": "To alert users of offers, restocks, or cart reminders instantly.",
            "insight_423": "It tests multiple page variations simultaneously to improve UX.",
            "insight_424": "It shows how users navigate from discovery to checkout.",
            "insight_425": "By adjusting prices dynamically based on demand and competitor trends.",
            "insight_426": "They reflect changing customer behavior in digital commerce.",
            "insight_427": "Ensuring optimal product variety without overcomplicating inventory.",
            "insight_428": "To measure retention and predict long-term customer value.",
            "insight_429": "It identifies which marketing touchpoint led to a sale.",
            "insight_430": "By following WCAG guidelines for inclusive design.",
            "insight_431": "It directly affects willingness to share payment information.",
            "insight_432": "To send personalized messages to specific customer groups.",
            "insight_433": "By measuring correct order deliveries versus total orders.",
            "insight_434": "It prioritizes potential customers most likely to convert.",
            "insight_435": "It centralizes customer data for improved relationship management.",
            "insight_436": "Informed customers make faster, more confident purchases.",
            "insight_437": "Stock shortages lead to missed revenue opportunities.",
            "insight_438": "By using user suggestions to refine website features.",
            "insight_439": "They improve accessibility for diverse language users.",
            "insight_440": "It enables smooth communication between systems as business grows.",
            "insight_441": "It provides insight into overall relationship profitability.",
            "insight_442": "They increase affordability and purchase likelihood for high-value items.",
            "insight_443": "AI anticipating issues before customers report them.",
            "insight_444": "It measures which campaigns are most profitable.",
            "insight_445": "Through filters, search algorithms, and personalization.",
            "insight_446": "Accurate inventory builds credibility with customers.",
            "insight_447": "It reflects how effectively abandoned carts are converted.",
            "insight_448": "They ensure compliance and optimize data storage usage.",
            "insight_449": "It shows which categories drive maximum profitability.",
            "insight_450": "By automating workflows with integrated payment APIs.",
            "insight_451": "AI-driven predictions of what customers are likely to buy next.",
            "insight_452": "It resonates better with regional audiences and increases trust.",
            "insight_453": "By using AI chatbots and intelligent routing systems.",
            "insight_454": "It provides convenience and faster checkout for customers.",
            "insight_455": "It indicates brand visibility and campaign effectiveness.",
            "insight_456": "It reduces errors and increases fulfillment speed.",
            "insight_457": "Downtime directly leads to lost sales opportunities.",
            "insight_458": "By adding auto-suggestions, spelling corrections, and filters.",
            "insight_459": "To prevent loss of sales during gateway outages.",
            "insight_460": "It reflects brand stickiness and customer interest.",
            "insight_461": "By using web scraping tools and price monitoring APIs.",
            "insight_462": "It increases loyalty and encourages feedback collection.",
            "insight_463": "By identifying items with high probability of return.",
            "insight_464": "A measure of how quickly inventory is sold and replaced.",
            "insight_465": "To assess product appeal and conversion efficiency.",
            "insight_466": "They consolidate insights for fast strategic decision-making.",
            "insight_467": "To visually identify engagement zones and optimize layout.",
            "insight_468": "By analyzing ad performance and conversion trends.",
            "insight_469": "It enhances user experience by showing products virtually.",
            "insight_470": "To improve inventory control and order accuracy.",
            "insight_471": "By analyzing transaction anomalies and user patterns.",
            "insight_472": "Globalization and better logistics enable international sales.",
            "insight_473": "Through ROI, engagement rate, and conversion metrics.",
            "insight_474": "They help monitor progress toward strategic objectives.",
            "insight_475": "Strong growth expected due to increasing smartphone penetration and digital payment adoption.",
            "insight_476": "By using insights to optimize pricing, stock, and marketing strategies.",
            "insight_477": "It focuses on value creation and long-term loyalty."
        }
    }
]

conversation_history: Dict[str, list] = {}

def update_history(user: str, question: str, bot_response: str) -> None:
    """Update in-memory conversation_history and save to DB."""
    # update in-memory structure
    if user not in conversation_history:
        conversation_history[user] = []
    conversation_history[user].append({
        "question": question,
        "response": bot_response,
        "timestamp": datetime.utcnow().isoformat()
    })

    # persist to sqlite via DataBase.save_conversation
    try:
        save_conversation(user, question, bot_response)
    except Exception as e:
        # keep failing silently but log for debugging
        print("⚠️ Failed to save conversation to DB:", e)
